import { activeDates, inclusiveDays } from "./date-utils";
import type { Challenge, ExerciseSet } from "@/types";
const live=(sets:ExerciseSet[])=>sets.filter(s=>!s.deletedAt);
export interface TotalProgress { recordedTotal:number; currentTotal:number; remaining:number; expectedByToday:number|null; deficit:number; aheadBy:number; daysRemaining:number|null; requiredDailyAverage:number|null; completionPercent:number; }
export function totalProgress(challenge:Challenge,sets:ExerciseSet[],today:string):TotalProgress{
 const recordedTotal=live(sets).filter(s=>s.challengeId===challenge.id).reduce((n,s)=>n+s.reps,0); const currentTotal=challenge.openingReps+recordedTotal; const remaining=Math.max(challenge.targetReps-currentTotal,0); const completionPercent=Math.min(currentTotal/challenge.targetReps*100,100);
 if(!challenge.endDate)return{recordedTotal,currentTotal,remaining,expectedByToday:null,deficit:0,aheadBy:0,daysRemaining:null,requiredDailyAverage:null,completionPercent};
 const bounded=today<challenge.startDate?challenge.startDate:today>challenge.endDate?challenge.endDate:today; const expectedByToday=challenge.targetReps*inclusiveDays(challenge.startDate,bounded)/inclusiveDays(challenge.startDate,challenge.endDate); const deficit=Math.max(Math.ceil(expectedByToday-currentTotal),0); const aheadBy=Math.max(Math.floor(currentTotal-expectedByToday),0); const tomorrow=new Date(`${today}T12:00:00`); tomorrow.setDate(tomorrow.getDate()+1); const tomorrowString=tomorrow.toISOString().slice(0,10); const daysRemaining=today>=challenge.endDate?0:inclusiveDays(tomorrowString,challenge.endDate); const requiredDailyAverage=daysRemaining>0?Math.ceil(remaining/daysRemaining):remaining;
 return{recordedTotal,currentTotal,remaining,expectedByToday,deficit,aheadBy,daysRemaining,requiredDailyAverage,completionPercent};
}
export interface DailyProgress { todayTotal:number; todayRemaining:number; todayCompletionPercent:number; successfulDays:number; missedDays:number; streak:number; periodExpected:number; periodActual:number; periodDeficit:number; }
export function dailyProgress(challenge:Challenge,sets:ExerciseSet[],today:string):DailyProgress{
 const relevant=live(sets).filter(s=>s.challengeId===challenge.id); const todayTotal=relevant.filter(s=>s.localDate===today).reduce((n,s)=>n+s.reps,0); const end=challenge.endDate&&challenge.endDate<today?challenge.endDate:today; const dates=activeDates(challenge.startDate,end,challenge.activeWeekdays); const totals=new Map<string,number>(); relevant.forEach(s=>totals.set(s.localDate,(totals.get(s.localDate)||0)+s.reps)); const successfulDays=dates.filter(d=>(totals.get(d.toISOString().slice(0,10))||0)>=challenge.targetReps).length; const completed=dates.filter(d=>d.toISOString().slice(0,10)<today); const missedDays=completed.length-completed.filter(d=>(totals.get(d.toISOString().slice(0,10))||0)>=challenge.targetReps).length; let streak=0; for(let i=dates.length-1;i>=0;i--){const key=dates[i].toISOString().slice(0,10); if(key===today&&todayTotal<challenge.targetReps)continue; if((totals.get(key)||0)>=challenge.targetReps)streak++;else break;}
 const periodExpected=challenge.targetReps*dates.length; const periodActual=challenge.openingReps+relevant.filter(s=>s.localDate>=challenge.startDate&&s.localDate<=end).reduce((n,s)=>n+s.reps,0); return{todayTotal,todayRemaining:Math.max(challenge.targetReps-todayTotal,0),todayCompletionPercent:Math.min(todayTotal/challenge.targetReps*100,100),successfulDays,missedDays,streak,periodExpected,periodActual,periodDeficit:Math.max(periodExpected-periodActual,0)};
}
